client:
  connection:
    host: http://ip.or.host:3000
  watcher:
    watch:
      # Directories and files to be watched.
      # Make sure the first item is a directory if you want to be able to do a full sync.
      # Examples:
      # - /path/to/dir
      # - '*.js'
      # - file.yml
      - 'path/to/dir'
    ignore:
      # Directories and files to be ignored.
      # Examples:
      # - /path/to/dir
      # - '**/.idea'
      # - {**/.idea,**/.idea/**,**/.idea/.**}
      # - '*.xml'
      # - file.js
      - '{**/.idea,**/.idea/**,**/.idea/.**}'
server:
  path: 'path/to/dir'
  connection:
    port: 3000
security:
  secret: 'changeme'
